-- Database Initialization Script
-- Generated by ProjexLight CLI Export System
-- Project: ProjexCloud
-- Database: postgresql
-- Auto-executed when Docker container is first created
-- Location: ./init-scripts/01-schema.sql
-- Schema Hash: e10808d43975dc40

-- ========================================
-- SCHEMA VERSION TRACKING (For Multi-Developer Sync)
-- ========================================
-- This table tracks the current schema version in your local database.
-- The MCP Schema Sync Agent uses this to detect changes and sync with ProjexLight.

CREATE TABLE IF NOT EXISTS _schema_version (
    id SERIAL PRIMARY KEY,
    schema_hash VARCHAR(64) NOT NULL,
    version INTEGER DEFAULT 1,
    applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    source VARCHAR(50) DEFAULT 'init'  -- 'init', 'migration', 'sync'
);

-- ========================================
-- APPLICATION SCHEMA
-- ========================================

-- User-Defined Database Schemas
-- Generated by ProjexLight CLI Export System
-- Database: postgresql
-- Total Schemas: 1

-- ========================================
-- Schema: ProjexCloud Schema
-- Description: Auto-generated database schema for ProjexCloud. Prototype structure for nextjs + fastify + postgresql MVP focused on auth, vault key management, routing, and audit chain....
-- Version: 1
-- ========================================

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid()
,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE users IS 'Schema: ProjexCloud Schema - Entity: Users';

CREATE TABLE IF NOT EXISTS keys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid()
,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE keys IS 'Schema: ProjexCloud Schema - Entity: Keys';

CREATE TABLE IF NOT EXISTS audit_ledger (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid()
,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE audit_ledger IS 'Schema: ProjexCloud Schema - Entity: Audit_ledger';

CREATE TABLE IF NOT EXISTS schema_version (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  schema_hash VARCHAR(255),
  version INTEGER DEFAULT 1,
  applied_at TIMESTAMP WITH TIME ZONE DEFAULT 'NOW()',
  source VARCHAR(255) DEFAULT 'INIT',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE schema_version IS 'Schema: ProjexCloud Schema - Entity: _schema_version';

CREATE TABLE IF NOT EXISTS migrations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sdk TEXT,
  filename TEXT,
  sha256 TEXT,
  applied_at VARCHAR(255) DEFAULT 'now()',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE migrations IS 'Schema: ProjexCloud Schema - Entity: _migrations';


-- ========================================
-- SAMPLE DATA (Optional)
-- ========================================
-- Uncomment and modify the following to add sample data:

-- INSERT INTO users (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO keys (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO audit_ledger (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO schema_version (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO migrations (column1, column2) VALUES ('value1', 'value2');

-- ========================================
-- RECORD INITIAL SCHEMA VERSION
-- ========================================
INSERT INTO _schema_version (schema_hash, version, source) VALUES ('e10808d43975dc40', 1, 'init');

-- ========================================
-- SCRIPT COMPLETED
-- ========================================
