import type { LegalExportJurisdiction } from '@projexlight/contracts';

/**
 * Jurisdiction-specific render fragments for the legal-export PDF.
 *
 * Each template returns the strings the bundler renders into the PDF:
 *   - title (cover page)
 *   - certification clause (signed by ProjexCloud + counter-sign)
 *   - chain-of-custody declaration (per-jurisdiction wording)
 *   - required regulatory disclosures (e.g. GDPR Art. 15 reference)
 *
 * Out of scope for this drop: actual notarization, court-specific
 * stamps, attorney-of-record fields. Those land per-customer as the
 * legal review (PRD §9 dependency) completes.
 */

export interface JurisdictionTemplate {
  jurisdiction: LegalExportJurisdiction;
  title: string;
  certification: string;
  chain_clause: string;
  disclosures: string[];
  /** Localized timestamp format hint for the bundler. */
  timezone_hint: string;
}

const US_COURT: JurisdictionTemplate = {
  jurisdiction: 'us-court',
  title: 'Chain-of-Custody Evidence Export — US Federal/State Court',
  certification:
    'I hereby certify under penalty of perjury that the digital evidence enclosed has been preserved, transferred, and produced in accordance with FRE 901(b)(9) (process or system) and FRE 902(13) (certified records). The chain-of-custody hashes recorded herein were computed at capture time and verified at export time.',
  chain_clause:
    'Each capture is identified by a unique capture_id and is bound to the encounter, device attestation, GPS coordinate, IMU signature, and consent receipt in effect at the moment of capture. Subsequent transfers, edits, watermarks, and accesses are recorded as append-only entries in the chain-of-custody log; the integrity of the chain is cryptographically verifiable via the SHA-256 hash linkage.',
  disclosures: [
    'This export was generated by ProjexCloud Evidence SDK v1.0.0 under FRE-compliant chain-of-custody discipline.',
    'Tamper detection: any byte-level modification of the bundled PDF or JSONL manifest will invalidate the signature envelope on the cover page.',
  ],
  timezone_hint: 'America/New_York',
};

const EU_GDPR: JurisdictionTemplate = {
  jurisdiction: 'eu-gdpr',
  title: 'Digital Evidence Export — EU GDPR Subject Access (Art. 15)',
  certification:
    'The data controller certifies that the personal data included in this export has been gathered, processed, and produced in conformity with Regulation (EU) 2016/679 (GDPR). All lawful bases for processing are recorded in the consent_ref column; data minimization has been applied per Art. 5(1)(c).',
  chain_clause:
    'Each capture row references the consent receipt under which it was collected. Where the data subject has exercised the right to erasure (Art. 17), affected captures are marked status=shredded and the corresponding storage objects have been cryptographically rendered unrecoverable (Art. 32(1)(a) "pseudonymisation and encryption").',
  disclosures: [
    'Data subject rights: Art. 15 (access), Art. 16 (rectification), Art. 17 (erasure), Art. 18 (restriction), Art. 20 (portability), Art. 21 (objection).',
    'Controller contact: see consent_receipt_controller_email column in the JSONL manifest.',
    'Supervisory authority: data subjects may lodge a complaint with their member-state DPA per Art. 77.',
  ],
  timezone_hint: 'Europe/Berlin',
};

const INDIA_IT_ACT: JurisdictionTemplate = {
  jurisdiction: 'india-it-act',
  title: 'Electronic Evidence Export — India (IT Act §65B; DPDP Act 2023)',
  certification:
    'I, the authorized signatory, certify under §65B(4) of the Indian Evidence Act, 1872 (as amended by the Information Technology Act, 2000) that the electronic record produced herein was generated by a computer system operated regularly during the relevant period and that the integrity of the record has been preserved through the recorded chain-of-custody hashes.',
  chain_clause:
    'Each capture row carries the device_uuid of the producing computer system, the persona_id of the operator, and the consent reference in force per the Digital Personal Data Protection Act, 2023. The chain-of-custody log is append-only and cryptographically linked entry-to-entry.',
  disclosures: [
    '§65B(4) compliance: this certificate is signed by the person occupying a responsible official position in relation to the operation of the device.',
    'DPDP Act 2023: data principal rights of access, correction, and erasure are mediated via the consent manager identified in the consent_ref.',
  ],
  timezone_hint: 'Asia/Kolkata',
};

const DEFAULT_TEMPLATE: JurisdictionTemplate = {
  jurisdiction: 'us-court',
  title: 'Digital Evidence Export — Default (Jurisdiction-Neutral)',
  certification:
    'This export was generated by ProjexCloud Evidence SDK with chain-of-custody integrity verified at export time. Jurisdiction-specific certifications were not requested; counsel should select a registered jurisdiction template before relying on this bundle in formal proceedings.',
  chain_clause:
    'Each capture is bound to its encounter, device, consent receipt, and GPS coordinate at capture time. The chain-of-custody log records every subsequent action with SHA-256 hash linkage.',
  disclosures: [
    'Configure a jurisdiction in the export request to receive jurisdiction-specific clauses.',
  ],
  timezone_hint: 'UTC',
};

const TEMPLATES: Record<string, JurisdictionTemplate> = {
  'us-court': US_COURT,
  'eu-gdpr': EU_GDPR,
  'india-it-act': INDIA_IT_ACT,
};

export function getJurisdictionTemplate(jurisdiction: LegalExportJurisdiction): JurisdictionTemplate {
  return TEMPLATES[jurisdiction] ?? DEFAULT_TEMPLATE;
}

export function registerJurisdictionTemplate(template: JurisdictionTemplate): void {
  TEMPLATES[template.jurisdiction] = template;
}

export function listJurisdictionTemplates(): JurisdictionTemplate[] {
  return Object.values(TEMPLATES);
}
