-- Migration 004: durable runtime support for sdk-workflow.
--
-- The synthetic in-process runner from migrations 001-003 executes every step
-- inside the calling request and dies if the pod restarts mid-run. It also
-- can't survive long `sleep:<ms>` markers because nothing wakes the run back
-- up after the process forgets it.
--
-- This migration adds the Postgres-backed durability primitives the
-- leveraged-locked polling worker needs:
--   - workflow.run.wake_at + status='paused' so a run can park itself.
--   - workflow.run.current_idx so the worker knows which step to resume from.
--   - workflow.run.claimed_by / claimed_at for diagnostic visibility (the
--     actual race-safety comes from FOR UPDATE SKIP LOCKED in the tick).
--   - workflow.step.wake_at so per-step sleep windows are visible per row.
--   - An index on (wake_at) WHERE paused so the polling worker's hot query
--     is an index range scan, not a seq scan over every run ever.
--
-- The `sleep:<duration_ms>` step naming convention does NOT require a CHECK
-- constraint change — the existing workflow.step.name column is unconstrained
-- TEXT and the runtime engine recognizes the prefix at execution time.

-- workflow.run: paused state, wake timer, resume cursor, lease diagnostics.
ALTER TABLE workflow.run
  ADD COLUMN IF NOT EXISTS wake_at      TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS current_idx  INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS claimed_by   TEXT,
  ADD COLUMN IF NOT EXISTS claimed_at   TIMESTAMPTZ;

-- Alter status CHECK constraint to permit 'paused'. The original constraint
-- name is auto-generated by Postgres for the inline CHECK in 001 — look it up
-- via pg_constraint and drop-then-recreate under a stable name.
DO $$
DECLARE
  c_name TEXT;
BEGIN
  -- Drop the existing status check (auto-named) if present.
  SELECT conname INTO c_name
    FROM pg_constraint
   WHERE conrelid = 'workflow.run'::regclass
     AND contype = 'c'
     AND pg_get_constraintdef(oid) ILIKE '%status%running%completed%';
  IF c_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE workflow.run DROP CONSTRAINT %I', c_name);
  END IF;

  -- Drop our stable-named one too in case this migration is re-run.
  IF EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'run_status_check'
       AND conrelid = 'workflow.run'::regclass
  ) THEN
    ALTER TABLE workflow.run DROP CONSTRAINT run_status_check;
  END IF;

  ALTER TABLE workflow.run
    ADD CONSTRAINT run_status_check
    CHECK (status IN ('running','paused','completed','failed','compensated','terminated'));
END
$$;

-- workflow.step: per-step sleep window (NULL = step does not sleep).
ALTER TABLE workflow.step
  ADD COLUMN IF NOT EXISTS wake_at TIMESTAMPTZ;

-- Hot path for the polling worker: find paused runs ready to resume.
-- Partial index keeps it tiny — only paused runs with a wake target.
CREATE INDEX IF NOT EXISTS run_wake_idx
  ON workflow.run (wake_at)
  WHERE wake_at IS NOT NULL AND status = 'paused';

COMMENT ON COLUMN workflow.run.wake_at     IS 'When a paused run becomes eligible for resume by the durable worker. NULL unless status=paused.';
COMMENT ON COLUMN workflow.run.current_idx IS 'Index of the next step_specs[] entry to execute on resume.';
COMMENT ON COLUMN workflow.run.claimed_by  IS 'Diagnostic: identity of the worker that last claimed this run. Lock is FOR UPDATE SKIP LOCKED, not this column.';
COMMENT ON COLUMN workflow.run.claimed_at  IS 'Diagnostic: when the current worker claimed this run.';
COMMENT ON COLUMN workflow.step.wake_at    IS 'For sleep:<ms> steps, the wall-clock target when the run should resume.';
