#!/bin/bash
#===============================================================================
# Generate missing tests/api_definitions/*.json files from api_library DB
#===============================================================================
# Reads api_library rows for the current project and creates JSON definition
# files for any endpoints that don't already have local definition files.
#
# Usage:
#   ./mcp-server/generate-missing-api-defs.sh [api_library_dump.jsonl]
#
# If no argument given, expects the dump at tmp-compare/api-library-full-dump.jsonl
# (generated by the SQL dump command in the sprint_id investigation).
#
# The generated files follow the standard tests/api_definitions/ naming convention:
#   tests/api_definitions/<resource>-<action>.json
#
# Each file includes:
#   - name, endpoint, method (from api_library)
#   - requiresAuth (inferred from auth_type)
#   - expectedStatus (from test_data_sets or defaults)
#   - testCases (from test_data_sets if available)
#   - captureResponse (from response_variables)
#   - dependsOn (from dependencies)
#   - taskId, sprintId, featureId (from api_library context)
#
# Run once to catch up on missing definitions. Future tasks should create
# definition files via the enforced step 4b.1 in the LLM workflow.
#===============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
API_DEFS_DIR="$PROJECT_ROOT/tests/api_definitions"
DUMP_FILE="${1:-$PROJECT_ROOT/tmp-compare/api-library-full-dump.jsonl}"

if [ ! -f "$DUMP_FILE" ]; then
    echo "ERROR: API library dump file not found: $DUMP_FILE"
    echo "Generate it with:"
    echo "  PGPASSWORD='...' psql -h <host> -p <port> -U appgen -d aiappgen -tA -c \\"
    echo "  \"SELECT json_build_object('endpoint', api_endpoint, 'method', http_method, ...) FROM api_library WHERE project_id='...';\""
    echo "  > tmp-compare/api-library-full-dump.jsonl"
    exit 1
fi

if ! command -v python3 &>/dev/null; then
    echo "ERROR: python3 required"
    exit 1
fi

mkdir -p "$API_DEFS_DIR"

python3 << 'PYEOF'
import json, os, re, sys

api_defs_dir = os.environ.get('API_DEFS_DIR', 'tests/api_definitions')
dump_file = os.environ.get('DUMP_FILE', 'tmp-compare/api-library-full-dump.jsonl')

# Load existing definition files to know what we already have
existing = set()
for root, dirs, files in os.walk(api_defs_dir):
    for f in files:
        if f.endswith('.json'):
            try:
                with open(os.path.join(root, f)) as fh:
                    d = json.load(fh)
                    ep = d.get('endpoint') or d.get('url') or d.get('api_endpoint', '')
                    method = (d.get('method') or d.get('http_method', 'GET')).upper()
                    if ep:
                        existing.add((method, ep))
            except Exception:
                pass

print(f"Found {len(existing)} existing definition files")

# Read the api_library dump
rows = []
with open(dump_file) as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        try:
            rows.append(json.loads(line))
        except json.JSONDecodeError:
            pass

print(f"Loaded {len(rows)} api_library rows")

# Find missing ones
created = 0
skipped = 0
for row in rows:
    endpoint = row.get('endpoint', '')
    method = (row.get('method') or 'GET').upper()

    if not endpoint or not endpoint.startswith('/api/'):
        skipped += 1
        continue

    if (method, endpoint) in existing:
        skipped += 1
        continue

    # Generate a sensible filename
    # /api/auth/register → auth-register
    # /api/documents/:id/tags → documents-id-tags
    path_parts = endpoint.replace('/api/', '').strip('/').split('/')
    slug = '-'.join(p.replace(':', '').replace('*', '') for p in path_parts if p)
    if not slug:
        slug = 'root'
    filename = f"{slug}-{method.lower()}.json" if method != 'GET' else f"{slug}.json"
    # Deduplicate if collision
    filepath = os.path.join(api_defs_dir, filename)
    counter = 1
    while os.path.exists(filepath):
        filepath = os.path.join(api_defs_dir, f"{slug}-{method.lower()}-{counter}.json")
        counter += 1

    # Determine auth requirement
    auth_type = row.get('auth_type') or 'bearer'
    requires_auth = auth_type not in ('none', 'public', '')

    # Build test cases from test_data_sets if available
    tds = row.get('test_data_sets') or []
    if isinstance(tds, str):
        try:
            tds = json.loads(tds)
        except Exception:
            tds = []
    if not isinstance(tds, list):
        tds = [tds] if isinstance(tds, dict) else []

    test_cases = []
    for tc in tds[:3]:
        if not isinstance(tc, dict):
            continue
        case = {
            "name": tc.get('name', f"Test case"),
            "payload": tc.get('variables', tc.get('body', {})),
            "expectedStatus": tc.get('expected_response', {}).get('status', 200) if isinstance(tc.get('expected_response'), dict) else 200,
            "headers": tc.get('headers', {})
        }
        if requires_auth and not case['headers'].get('Authorization'):
            case['headers']['Authorization'] = 'Bearer {{cache:auth.login.response.data.token}}'
        test_cases.append(case)

    # Default test case if none from DB
    if not test_cases:
        default_case = {
            "name": f"Default {method} test",
            "expectedStatus": 200 if method == 'GET' else 201 if method == 'POST' else 200,
        }
        if method in ('POST', 'PUT', 'PATCH'):
            sample = row.get('sample_input') or row.get('request_body_template') or {}
            if isinstance(sample, str):
                try:
                    sample = json.loads(sample)
                except Exception:
                    sample = {}
            default_case['payload'] = sample if isinstance(sample, dict) else {}
        if requires_auth:
            default_case['headers'] = {'Authorization': 'Bearer {{cache:auth.login.response.data.token}}'}
        test_cases.append(default_case)

    # Build dependsOn from dependencies field
    deps = row.get('dependencies') or []
    if isinstance(deps, str):
        try:
            deps = json.loads(deps)
        except Exception:
            deps = []
    depends_on = []
    for dep in (deps if isinstance(deps, list) else []):
        if isinstance(dep, dict) and dep.get('source'):
            depends_on.append(dep['source'])

    # Add implicit auth dependency for protected routes
    if requires_auth and 'POST /api/auth/login' not in depends_on and endpoint not in ('/api/auth/login', '/api/auth/register'):
        depends_on = ['POST /api/auth/register', 'POST /api/auth/login'] + depends_on

    # Build captureResponse from response_variables
    rv = row.get('response_variables') or []
    if isinstance(rv, str):
        try:
            rv = json.loads(rv)
        except Exception:
            rv = []
    capture = {}
    for v in (rv if isinstance(rv, list) else []):
        if isinstance(v, dict) and v.get('name') and v.get('path'):
            capture[v['name']] = v['path']

    # Assemble the definition
    definition = {
        "name": row.get('name', f"{method} {endpoint}"),
        "endpoint": endpoint,
        "method": method,
        "requiresAuth": requires_auth,
        "expectedStatus": test_cases[0].get('expectedStatus', 200) if test_cases else 200,
        "taskId": row.get('task_id'),
        "sprintId": row.get('sprint_id'),
        "featureId": row.get('feature_id'),
        "testCases": test_cases,
        "dependsOn": depends_on if depends_on else [],
        "captureResponse": capture if capture else {},
        "_generated": True,
        "_source": "api_library_backfill"
    }

    with open(filepath, 'w') as out:
        json.dump(definition, out, indent=2)
    created += 1
    existing.add((method, endpoint))
    print(f"  + {filepath}")

print(f"\nDone: {created} files created, {skipped} skipped (already exist or invalid)")
PYEOF