-- User-Defined Database Schemas
-- Generated by ProjexLight CLI Export System
-- Database: postgresql
-- Total Schemas: 1

-- ========================================
-- Schema: ProjexCloud Schema
-- Description: Auto-generated database schema for ProjexCloud. Prototype structure for nextjs + fastify + postgresql MVP focused on auth, vault key management, routing, and audit chain....
-- Version: 1
-- ========================================

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid()
,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE users IS 'Schema: ProjexCloud Schema - Entity: Users';

CREATE TABLE IF NOT EXISTS keys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid()
,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE keys IS 'Schema: ProjexCloud Schema - Entity: Keys';

CREATE TABLE IF NOT EXISTS audit_ledger (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid()
,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE audit_ledger IS 'Schema: ProjexCloud Schema - Entity: Audit_ledger';

CREATE TABLE IF NOT EXISTS schema_version (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  schema_hash VARCHAR(255),
  version INTEGER DEFAULT 1,
  applied_at TIMESTAMP WITH TIME ZONE DEFAULT 'NOW()',
  source VARCHAR(255) DEFAULT 'INIT',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE schema_version IS 'Schema: ProjexCloud Schema - Entity: _schema_version';

CREATE TABLE IF NOT EXISTS migrations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sdk TEXT,
  filename TEXT,
  sha256 TEXT,
  applied_at VARCHAR(255) DEFAULT 'now()',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE migrations IS 'Schema: ProjexCloud Schema - Entity: _migrations';

