/**
 * @projexlight/meter-codegen - AC-12 implementation.
 *
 * Scans TypeScript source for `@meter('sku', 'unit', 'tier')` decorator usage,
 * extracts the metadata, and emits a generated `meter.gen.ts` per package
 * containing the registry of every decorated method.
 *
 * The build-time codegen complements the runtime `@meter` decorator from
 * sdk-meter: it lets the platform inventory billable methods without running
 * the code, and feeds the billing-catalog spreadsheet.
 *
 * Usage (programmatic):
 *   import { scanPackage } from '@projexlight/meter-codegen';
 *   const entries = scanPackage('packages/sdk-vault/src');
 *
 * Usage (CLI):
 *   npx projex-meter-codegen --root packages/sdk-vault/src
 */

import fs from 'fs';
import path from 'path';
import ts from 'typescript';

export interface MeterDecoratorEntry {
  qualifiedName: string;
  sku: string;
  unit: string;
  tier: string;
  sourceFile: string;
  line: number;
}

function visit(
  node: ts.Node,
  sourceFile: ts.SourceFile,
  enclosingClass: string | null,
  out: MeterDecoratorEntry[],
): void {
  if (ts.isClassDeclaration(node) || ts.isClassExpression(node)) {
    const className = node.name?.text ?? '<anonymous>';
    ts.forEachChild(node, (c) => visit(c, sourceFile, className, out));
    return;
  }

  if (ts.isMethodDeclaration(node) || ts.isFunctionDeclaration(node)) {
    const decorators = ts.canHaveDecorators(node) ? ts.getDecorators(node) : undefined;
    if (decorators) {
      for (const d of decorators) {
        if (!ts.isCallExpression(d.expression)) continue;
        const callee = d.expression.expression;
        if (!ts.isIdentifier(callee) || callee.text !== 'meter') continue;
        const args = d.expression.arguments;
        if (args.length < 1) continue;
        const sku = ts.isStringLiteral(args[0]) ? args[0].text : '';
        const unit = args[1] && ts.isStringLiteral(args[1]) ? args[1].text : 'call';
        const tier = args[2] && ts.isStringLiteral(args[2]) ? args[2].text : 'core';
        const methodName = ts.isFunctionDeclaration(node)
          ? (node.name?.text ?? '<anonymous>')
          : (node.name && ts.isIdentifier(node.name) ? node.name.text : '<anonymous>');
        const qualifiedName = enclosingClass ? `${enclosingClass}.${methodName}` : methodName;
        const { line } = sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile));
        out.push({ qualifiedName, sku, unit, tier, sourceFile: sourceFile.fileName, line: line + 1 });
      }
    }
  }

  ts.forEachChild(node, (c) => visit(c, sourceFile, enclosingClass, out));
}

function listTsFiles(root: string): string[] {
  const out: string[] = [];
  if (!fs.existsSync(root)) return out;
  const stack: string[] = [root];
  while (stack.length > 0) {
    const cur = stack.pop()!;
    const stat = fs.statSync(cur);
    if (stat.isDirectory()) {
      if (path.basename(cur) === 'node_modules' || path.basename(cur) === 'dist') continue;
      for (const e of fs.readdirSync(cur)) stack.push(path.join(cur, e));
    } else if (stat.isFile() && (cur.endsWith('.ts') || cur.endsWith('.tsx'))) {
      out.push(cur);
    }
  }
  return out;
}

/**
 * Scans every .ts/.tsx file under `root` and returns the list of `@meter(...)`
 * decorator usages found.
 */
export function scanPackage(root: string): MeterDecoratorEntry[] {
  const entries: MeterDecoratorEntry[] = [];
  for (const fp of listTsFiles(root)) {
    const text = fs.readFileSync(fp, 'utf-8');
    const sourceFile = ts.createSourceFile(fp, text, ts.ScriptTarget.ES2022, true);
    visit(sourceFile, sourceFile, null, entries);
  }
  return entries;
}

/**
 * Emits a `meter.gen.ts` registering every found decorator into the runtime
 * registry exported by sdk-meter. Intended to be checked in OR added to
 * .gitignore + regenerated on build.
 */
export function emitMeterGen(entries: MeterDecoratorEntry[], outFile: string): void {
  const lines: string[] = [
    '/* AUTO-GENERATED by @projexlight/meter-codegen. DO NOT EDIT. */',
    `import { registerMeterMetadata } from '@projexlight/sdk-meter';`,
    '',
  ];
  for (const e of entries) {
    lines.push(
      `registerMeterMetadata(${JSON.stringify(e.qualifiedName)}, { sku: ${JSON.stringify(e.sku)}, unit: ${JSON.stringify(e.unit)} as never, tier: ${JSON.stringify(e.tier)} as never });`,
    );
  }
  lines.push('');
  lines.push(`export const METER_ENTRIES_COUNT = ${entries.length};`);
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, lines.join('\n'), 'utf-8');
}
